// Auto-generated by LocalisationTermGenerator.cs on 2026-03-18 23:34:36 (E. Australia Standard Time)
// Do not modify; changes will be overwritten

namespace FishFlingers.Localisation
{
	public enum LocalisationTerm
	{
		// Browse Games Panel
		BrowseGamesPanelTitle = 566923365,
		BrowseGamesPanelLan = -527790014,
		BrowseGamesPanelSteam = 1636470845,

		// Building Kit Panel
		BuildingKitPanelTitle = 1649053697,
		BuildingKitPanelBuild = 1582183131,

		// Characters
		CharactersRaftPlayerName = 814387201,
		CharactersRaftPlayerDescription = 1347063821,
		CharactersFlyingFishName = 1439338514,
		CharactersFlyingFishDescription = 936022047,

		// Common
		CommonQuit = 1749717008,

		// Entities
		EntitiesRaftTileName = 185241601,
		EntitiesRaftTileDescription = 1787465766,
		EntitiesDroppedItemName = -1941270485,
		EntitiesDroppedItemDescription = -1999990735,

		// Fishing Bag Panel
		FishingBagPanelTitle = -1857384445,

		// Main Menu Screen
		MainMenuScreenGameTitle = 1984598997,
		MainMenuScreenBrowseGames = -804614128,
		MainMenuScreenHostGame = 1510641791,

		// Structures
		StructuresWaveSignName = -490041344,
		StructuresWaveSignDescription = -708145142,
	}
}
